export const ROUTER = {
   Aсheck_endpoint: "proverka-endpointa",
   main: "/",
   news: "/novosti",
   newsArticle: "/novosti/:id",
   documents: "/documents",
   councilDeputies: {
      legalBasisActivity: "/pravovaya-osnova-deyatelnosti",
      symbolism: "/ustav-i-simvolika",
      deputies: {
         main: "/deputaty",
         deputies: "/deputaty",
         chart: "/deputaty/grafik-priyema-deputatov",
         awards: "/deputaty/nagrady-soveta-deputatov",
         rules: "/deputaty/pravila-deputatskoy-etiki",
      },
      compositionStructure: "/sostav-i-struktura",
      writeAdministration: "/napisat-v-administratsiyu",
   },
   contacts: {
      main: "/contacts",
   },
   search: "/search",

   admin: {
      main: '/admin',
      login: '/admin/login',
      news: '/admin/novost',
      newsArticle: '/admin/dobavit-novost',
      newsArticleEdit: '/admin/redaktirovat-novost/:id',
      documents: '/admin/dokumenty',
      documentsArticle: '/admin/dobavit-dokumenty',
      documentsArticleEdit: '/admin/redaktirovat-dokumenty/:id',
      deputies: '/admin/deputaty',
      deputiesArticle: '/admin/dobavit-deputaty',
      deputiesArticleEdit: '/admin/redaktirovat-deputaty/:id',
      internetResources: '/admin/internet-resursy',
      contacts: '/admin/kontakty',
      compositionParliamentaryGroups: '/admin/sostav-deputatskikh-grupp',
      scheduleReceptionDeputies: '/admin/redaktirovat-grafik-priyema-deputatov',
      legalBasisActivity: '/admin/pravovaya-osnova-deyatelnosti',
      charterAndSymbols: '/admin/ustav-i-simvolika',
      awardsTheCouncilDeputiesEdit: '/admin/redaktirovat-nagrady-soveta-deputatov',
      rulesParliamentaryEthicsEdit:'/admin/pravila-deputatskoy-etiki',
      compositionStandingCommitteesEdit:'/admin/sostav-postoyannykh-komissiy',
   },
};